#ifndef _PHYSICS_CONSTANTS_H
#define _PHYSICS_CONSTANTS_H

#define GRAVITY_CONSTANT 3.0f
#define TIME_CONSTANT 1.0f
#define FRICTION_CONSTANT 0.1f
#define RUNNING_CONSTANT 5.0f
#define JUMPING_CONSTANT 50.0f

#endif //_PHYSICS_CONSTANTS_H