#ifndef _PHYSICS_CONSTANTS_H
#define _PHYSICS_CONSTANTS_H

#define GRAVITY_CONSTANT 10.0f
#define TIME_CONSTANT 1.0f
#define FRICTION_CONSTANT 0.2f
#define RUNNING_CONSTANT 3.0f
#define JUMPING_CONSTANT 150.0f

#endif //_PHYSICS_CONSTANTS_H